document:
  type: Linee guida
  name: "Linee guida per il rilascio dell’identità digitale per uso professionale"
  short_name: Ll.gg. SPID Pro
  author: arbiastefano
  contributors:
    - Stefano Arbia
    - Walter Arrighetti
    - Michele D'Amico
    - Antonio Florio
    - Stefano Ianniello
    - Andrea Spallacci
  description: |
    Linee guida per il rilascio dell’identità digitale SPID ad uso professionale
  tags:
    - SPID
    - CAD
    - P.IVA
    - IdP
    - SP
    - SAML
  origin: https://github.com/test-lg/lg_SPID_uso-professionale/
